# Generated by Django 6.0 on 2025-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='azan/')),
            ],
        ),
    ]
