# Generated by Django 6.0 on 2025-12-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deen', '0002_azan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Azan',
        ),
    ]
